### ISSUE TITLE
X is still mentioned in the login and signup popup s

### ISSUE THREAD

**Issue by JustTemmie** [SauceyRed/bring-twitter-back#3]
unsure how much you care about this, as it's fairly minor

![image](https://github.com/SauceyRed/bring-twitter-back/assets/47639983/87290fd8-4640-41ab-92a3-8284f68a8105)
![image](https://github.com/SauceyRed/bring-twitter-back/assets/47639983/237d18b4-f537-4c9a-a32e-08a324cacf2e)

**Comment by Blackstareye** [comment]
I highlighted all locations on the login screen:
![grafik](https://github.com/SauceyRed/bring-twitter-back/assets/33430997/d7c22552-b168-4523-a7f8-856737db6f11)

edit: there is also one in the cookie banner

**Comment by SauceyRed** [comment]
Updated extension to replace "X" with "Twitter" in the footer and cookie banner. The "X" not being replaced only happens sometimes for me, not sure how to fix that, will look into it another time.
