### ISSUE TITLE
Twitter finally switched domains

### ISSUE THREAD

**Issue by nestalert** [SauceyRed/bring-twitter-back#4]
So, you should probably change the manifest from twitter.com to x.com?

**Comment by F121Live** [comment]
We were so back and then BOOM, billionaire schizophrenia kicks in :/

**Comment by Nescabir** [comment]
Made the change in this PR #5

**Comment by dec-mail** [comment]
Has the Moron finally screwed this app from working?

**Comment by m4n8tpr4** [comment]
Unfortunately, with version 2.1.3, there is some strange behaviour: while the Twitter bird appears permanently in the tab, on the web page, the X logo appears by default, and only sometimes changes randomly to the bird several seconds after the opening of a page.

**Comment by martymi** [comment]
I was having trouble getting this extension to work today with the x domain (ugh), finally got it working after clearing browser cache.

**Comment by dec-mail** [comment]
> Unfortunately, with version 2.1.3, there is some strange behaviour: while the Twitter bird appears permanently in the tab, on the web page, the X logo appears by default, and only sometimes changes randomly to the bird several seconds after the opening of a page.

must be that they are using/importing a different link/permalink/shortcode in some places

**Comment by dec-mail** [comment]
> I was having trouble getting this extension to work today with the x domain (ugh), finally got it working after clearing browser cache.

"Ugh".
It w/o question the most insane most stupid most insane stupid egotestical rebrandiun in history
And i mean that literally.

There are two diametrically opposite issues.

1. The Twitter brand and the blue birdie had ENORMOUS brand recognition and 'cachet' - which the Moron just casually simply trashed.
2.  'X' is simply a totally 'impossible' brand on so many different marketing branding levels.
 It is just insanely stupid.
